image: docker:19.03.15-dind

before_script:
  - docker info

lesson1:
  tags:
    - molecule-workshop
  stage: test
  script:
    - pwd
    - ls -lha
    - |
      docker run \
        --volume /var/run/docker.sock:/var/run/docker.sock \
        --volume $(pwd):$(pwd) \
        --workdir $(pwd)/lesson1_initialized_role/empty_role \
        --user root \
        quay.io/ansible/molecule:3.0.2 \
        /bin/sh -c "ls -lha && pip3 install testinfra && molecule test --all --parallel"

lesson2_empty:
  tags:
    - molecule-workshop
  stage: test
  script:
    - pwd
    - ls -lha
    - |
      docker run \
        --volume /var/run/docker.sock:/var/run/docker.sock \
        --volume $(pwd):$(pwd) \
        --workdir $(pwd)/lesson2_geerlingguy.docker/geerlingguy.docker \
        --user root \
        quay.io/ansible/molecule:3.0.2 \
        /bin/sh -c "ls -lha && pip3 install testinfra && molecule test --all --parallel"

lesson2_add_tests:
  tags:
    - molecule-workshop
  stage: test
  script:
    - pwd
    - ls -lha
    - |
      docker run \
        --volume /var/run/docker.sock:/var/run/docker.sock \
        --volume $(pwd):$(pwd) \
        --workdir $(pwd)/lesson2_geerlingguy.docker.add_tests/geerlingguy.docker \
        --user root \
        quay.io/ansible/molecule:3.0.2 \
        /bin/sh -c "ls -lha && pip3 install testinfra && molecule test --all --parallel"

lesson3:
  tags:
    - molecule-workshop
  stage: test
  script:
    - pwd
    - ls -lha
    - |
      docker run \
        --volume /var/run/docker.sock:/var/run/docker.sock \
        --volume $(pwd):$(pwd) \
        --workdir $(pwd)/lesson3_gererlinguy.docker.add_functionality/geerlingguy.docker \
        --user root \
        quay.io/ansible/molecule:3.0.2 \
        /bin/sh -c "ls -lha && pip3 install testinfra && molecule test --all --parallel"

lesson4:
  tags:
    - molecule-workshop
  stage: test
  script:
    - pwd
    - ls -lha
    - |
      docker run \
        --volume /var/run/docker.sock:/var/run/docker.sock \
        --volume $(pwd):$(pwd) \
        --workdir $(pwd)/lesson4_advanced_functionality.dependend_roles/some_role \
        --user root \
        quay.io/ansible/molecule:3.0.2 \
        /bin/sh -c "ls -lha && pip3 install testinfra && molecule test --all --parallel"

lesson5:
  tags:
    - molecule-workshop
  stage: test
  script:
    - pwd
    - ls -lha
    - |
      docker run \
        --volume /var/run/docker.sock:/var/run/docker.sock \
        --volume $(pwd):$(pwd) \
        --workdir $(pwd)/lesson5_advanced_functionality.advanced_inventories/some_role \
        --user root \
        quay.io/ansible/molecule:3.0.2 \
        /bin/sh -c "ls -lha && pip3 install testinfra && molecule test --all --parallel"