---
- name: "Install python3 pip"
  apt:
    name: python3-pip
    state: present

- name: "Install docker"
  pip:
    name:
      - docker
      - requests>=2.20.1
    executable: /usr/bin/pip3
    state: present

- name: "Run platform container"
  docker_container:
    name: ptl-whoami
    image: jwilder/whoami:latest
    state: started
    ports:
      - "8080:8000"
