---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=600
      when: ansible_os_family == 'Debian'
    - name: Ensure apt-utils
      apt:
        name:
          - apt-utils
        state: present
        force: true
      when: ansible_os_family == 'Debian'

  roles:
    - role: geerlingguy.docker
